version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Running Prisma migrations..."
      - npx prisma migrate deploy
      - echo "Generating Prisma Client..."
      - npx prisma generate
      - echo "Building the application..."
      - npm run build
  post_build:
    commands:
      - echo "Build completed. Artifacts ready for deployment."
artifacts:
  files:
    - package.json
    - package-lock.json
    - public/**/*
    - build/**/*
    - node_modules/.prisma/**/*
    - .ebextensions/**/*
  base-directory: "."
  discard-paths: no
