version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Running Prisma migrations..."
      #- npx prisma migrate deploy
      - echo "Building the application..."
      - npm run build # Optional, only if you have a build step
  post_build:
    commands:
      - echo "Build completed. Artifacts ready for deployment."
artifacts:
  files:
    - package.json
    - package-lock.json
    - public/**/*
    - build/**/*
    - .ebextensions/**/*
