# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d00e91671bfcbade21424ea745d30a77"
name = "dev-iagree-manual"
handle = "dev-iagree-manual"
application_url = "https://qty-because-gender-law.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dev-iagree-test.myshopify.com"

[auth]
redirect_urls = [
  "https://qty-because-gender-law.trycloudflare.com/auth/callback",
  "https://qty-because-gender-law.trycloudflare.com/auth/shopify/callback",
  "https://qty-because-gender-law.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
